### ISSUE TITLE
Reasonable data warehouse layers turned on by default

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#263]
As any/all users, I want reasonable data warehouse layers turned on by default in order to provide basic background content in addition to the physiographic map information.

**Additional Context**
- Layer 1 Municipality boundaries -  dashed red linework, no fill on the polygons
- Layer 2 Regional district boundaries -  dashed purple linework, no fill on the polygons
- Layer 3 Wells layers - circle symbol with an enclosed dot or line   Θ

**Acceptance Criteria**
- [x] Display the Muni / Reg at full province
- [ ] ~~For the Wells coverage - display as cluster pins that expand upon zoom - NOT Required~~
- [ ] ~~The Muni and RegDist layers need to have the linework as dashed red and dashed purple lines (not fill on these polygons)~~

**Comment by mikeshasko** [comment]
![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/6cf4f995-ea5e-455e-9da5-23da31558f18)

![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/1345519e-8dda-479d-9381-83bb1103e1a3)

**Comment by andrea-williams** [comment]
Confirmed with Mike Shasko the other day that we should not be pulling all wells in BC, since there are 10s/100s of thousands of them, and retrieving that data from the warehouse alone takes about 20 seconds, without adding all the icons to the map. Instead, wells are only retrieved within the bounding box defined by the viewing window of the map component, and only when the map is zoomed in to a certain level.
