### ISSUE TITLE
Export Observation Table with Foreign Keys to Treatments

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#269]
**As a** *any InvasivesBC user besides Data Viewer* **I want** *to export Observation Table with Foreign Keys to Treatment* **So That** *I can use the data in other 3rd party environments*

**Additional Context**
- Match inspect export but for InvasivesBC Observation data

**Acceptance Criteria**
- [x] Given I am on the Inventory page, When Click Export, Then a CSV of the observation table is downloaded to your local machine
- [x] Given I Clicked export, When the CSV is downloading, Then I can see the name of the file includes the date and time

**Comment by micheal-w-wells** [comment]
I vote metabase.

**Comment by micheal-w-wells** [comment]
I'll clarify a bit, you for sure might have a use case where it makes sense to custom build a csv export, or maybe this would be a substitute.  Even if you built your own, it would be worth it to get metabase spun up for Invasives because it gives you all kinds of free reporting/querying/exporting stuff out of the box.  If you want to expose it to a bunch of users check out how the MDS team integrated it into their app.
