### ISSUE TITLE
Fix Inspect CSV Export

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#303]
**Describe the Bug**
the current Export does not show all of the data needed by the users

**Expected Behaviour**
when we export it should have all data relevent to users

**Actual Behaviour**
some data is missing and the Journey details data is combined in a way that is not user friendly

**Acceptance Criteria**
- [ ] Any field that is inputted into the device should have a column on the CSV
- [x] also include "Created By" generated by DB
- [x] Journey details should have separate columns for Previous Waterbody and Destination Waterbody
- [x] Journey detail columns remain concatenated 
- [x] Export includes 'Other' Waterbody
- [x] Cross Reference Export against SchemaSpy

**Screenshots**

**Comment by andrea-williams** [comment]
I can only partially test this right now because I don't have an iPad so I can't submit any shifts/inspections myself.

Looking at the sample CSV file Pushan posted in Slack (March 20th), can confirm some acceptance criteria have been met. Also noticed some potential issues:

- the destination journey details column has "35 days out" concatenated on the end. I'm not sure if this is just an error with the dummy data, or if it's a problem in the app, but is the # days out of the waterbody applicable to the destination water body? I thought it was only for previous waterbodies
- some of the boolean fields, such as marineMusselFound, launchedOutsideBC, decontaminationPerformed, dryStorage, etc. have "NA" values in the CSV. Since these fields are part of the regular watercraft assessment schema (not high-risk), these fields should be applicable for all inspections. I'm guessing that there's some issue where False is being recorded as NA?
- all the fields that are part of the High Risk assessment section have "highRiskAssessment.<field-header>" as the column name. Do we need the "highRiskAssessment" part in the column name? By default in Excel the column width is much narrower than the column name, so at first glance all column names look the same. This is probably a question for PO @mikeshasko

**Comment by fwpushan** [comment]
Hi,
Data is dummy data,
1. Currently, API layer flattening the previous and destination waterbody
details as a comma-separated string.
2. There are some issues with Dummy Data.
3. Fixed issue with fields.

**Comment by andrea-williams** [comment]
Testing on this is blocked until bug in #301 (province of residence dropdown not rendering) is fixed.

**Comment by andrea-williams** [comment]
- timestamp for all inspections is 0:00
- number of people in party (Watercraft Details section) isn't exported to CSV
- "launchedOutsideBC" property appears in CSV file (always FALSE) but I'm not seeing this field in app form
- "destinationJourneyDetails" column lists both previous and destination waterbodies together, then "previousJourneyDetails" column is always empty
- destination waterbodies that have been submitted in the app are exported with "NaN days out" - this could be removed entirely, since days out doesn't apply to destination waterbodies
- I'm not sure if this actually matters, but the order of the columns in the CSV file doesn't match up with the order of fields in the app
- flagging this as a potential issue, but not sure: the "previousInspectionDays" column has a default of 0 if the watercraft has never been inspected previously. But 0 days since previous inspection kind of implies that it was inspected earlier the same day. Could we leave this field blank instead of defaulting to 0?

**Comment by fwpushan** [comment]
1. Amir is working to fix the timestamp issue. 
2. Number of people missing in db table, need a separate ticket to deal that 
3. Fixed 
4. Fixed 
5. Ordering is possible, please provide an expected behavior

**Comment by andrea-williams** [comment]
@fwpushan I'd suggest the order that the fields appear in the form as displayed in the app? Would probably make it easier for mussel admin users to map the CSV columns to the fields in the app. But I don't think this is an important concern - more just a UX thought.

**Comment by rajfreshworks** [comment]
The above mentioned issues related to the destination and previous waterbodies as well as the timestamp are fixed. I found out some other issues in the export

- As mentioned above, launchedOutsideBc still appears

- the field decontaminationReference appears twice 
    - `decontaminationReference`(always empty) 
    -  `highRiskAssessment. decontaminationReference`(has the right value).
We should remove the first one, unless those two are different

- Same issue with the comments field,
   - `generalComments`(has the right value) 
   - `highRiskAssessment.generalComments`(always NONE)

**Comment by fwpushan** [comment]
These are mostly database changes, I think we should have a different ticket for that. @jakemorr @mikeshasko
