### ISSUE TITLE
Updating SonarQube/OWASP Zap

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#452]
**Describe the task**
Updating sonar qube

**Acceptance Criteria**
- [x] sonar qube should be a build step in our pipeline

**Additional Context**
- SonarQube and Zap are part of the same image

**Comment by andrea-williams** [comment]
Helpful resource: https://github.com/BCDevOps/sonarqube

**Comment by andrea-williams** [comment]
Have submitted a request to labops to add lucy-web to SonarCloud projects:
https://github.com/BCDevOps/devops-requests/issues/359

**Comment by andrea-williams** [comment]
We have a lucy-web project on SonarCloud (https://sonarcloud.io/dashboard?id=bcgov_lucy-web) that performs automatic analysis for every PR. It doesn't produce a test coverage report because it's not running unit tests. Once we've moved away from Jenkins and onto GitHub Actions for our entire pipeline, we'll be able to run unit tests against our DB and produce a meaningful coverage report with nyc. 

In `.github/workflows/static-analysis.yml` there's a partially complete CI workflow for running unit tests & producing coverage reports. Major gotcha is that SonarCloud can't reconcile the LCOV files generated with our actual code files, because of differences in the filepaths because of the Docker container within which the GitHub Action is performed. See https://stackoverflow.com/questions/58871955/sonarcloud-code-coverage-remains-0-0-in-github-actions-build. I tried to rename the filepaths with regex like in the accepted answer but still wasn't able to get it working.
