### ISSUE TITLE
Status page to view records - Mobile

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#658]
**Description/details**
User needs to be able to see a list of records and the sync status. The user should be able to click on each record to open and edit if it hasn't been synced, and read only if already synced. 

**Additional Context**

- [ ] All observation/treatment/monitoring activities appear on a scroll-able list
- [ ] Edit / Delete / Sync functions will be built in subsequent issues
- [ ] Need manual "commit" button at bottom
- [ ] Fields to include in summary view for each record:
   - Details: 

REQUIRES subsequent tickets to:
- Sync all records
- Edit a selected record - move to the "review" page for plant or animal depending on the activity
- Delete a selected record off the device (provide "are you sure?" modal) then refresh list
- Attempt a sync of the selected record

**Comment by ghost** [comment]
Mobile landing page / status review page

![Status.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/2898bb9f-72ea-4c3e-9e17-feee3c58f6b0)

**Comment by ghost** [comment]
[‎2020-‎07-‎29 9:41 AM]  Simon, Zoe FLNR:EX:  
For ticket #658, it says that subsequent tickets need to be created to sync, edit, delete and attempt a sync ... those should get created for this upcoming sprint, right?

**Comment by ZoeSimon** [comment]
@victorchong and this one

**Comment by victorc-bcgov** [comment]
@anissa-agahchen If the four column implementation is problematic, we could tweak the content back into a 3-column view by

1. taking out the "date / time" and "status" fields and integrating them into the record divider; and
2. moving the "Delete" function into the record editing screen, vs. in the index.

There are two trending design paradigms for handling the deletion of records: deleting from the index of records, or deleting within the record itself. In this case, I would recommend deleting from within the record because it takes more steps to perform (which is a good thing, considering the amount of effort that will be lost), and also because we have no "undo" function.

For example (please use imagination):

--- Apr 12, 16:30: Comment Field Error ----------
Species -  Activity -  Area
Jurisdiction - Agency - EDIT

--- Apr 12, 14:30: Sync OK ----------
Species -  Activity -  Area
Jurisdiction - Agency

--- Apr 10, 09:25: Pending Sync ----------
Species -  Activity -  Area
Jurisdiction - Agency - EDIT

Note the lack of "Edit" button on the record which has already been synchronized.

@mikeshasko The proposed tweak would require a "Delete" button to be added to the corresponding "Review" page for plant and animal observations, i.e. #431 and #562. This button would only be visible when an existing record is being edited.

**Comment by ghost** [comment]
@anissa-agahchen 

Here's the mussel status page.

![IMG_0079.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/dd1ab866-12e0-4947-b99f-c9b4cb609586)
