### ISSUE TITLE
INFO: Inspect - Running Inventory of Bugs

### ISSUE THREAD

**Issue by ghost** [bcgov/lucy-web#712]

**Comment by ghost** [comment]
**Email July 17**
On shift end today I looked through my previous shift logs and I have one that will not sync.
Shift ID 616 done on June 17
Nathan Gallup

**Email July 18**
I have been having this issue with my iPad for Mission. I have 4 entries that will not sync and upload. Not sure what’s going on. I’ll try a different iPad today. 
Keighley Doerksen


**Email July 18**
I am not sure why but yesterday’s file was also unable to sync but when I tried twice this morning it was able to sync. In summary for files under my name that are unable to sync are:

July 3, 111 inspections, 21 blow  bys – I noticed the Radium was not recorded for station 
July 4, 51 inspections, 14 blow bys- I noticed one inspection is missing a time for inspection
July 14, 20 inspections, 10 blow bys – I do not notice anything missing

I am currently unable to make any changes to the documents while they are in pending sync status.  
Amie Nadeau 

**Email July 9**
Mike is there a way for Amie to still make an edit to the record if it was already submitting but the sync is still pending? 
Yes I believe it is a 300 character limit per comment section, correct Mike? 
Martina Beck

**Email July 16**
One question – after the entries are successfully synced for the shift, will they remain on the shift screen for the idir user indefinitely?  I always thought they may disappear after a successful shift but I may be wrong; please let me know.
Aaron Canuel

**Email July 16**
After talking with the crew the consensus is that our entries may not be syncing properly. When we submit them, they say the synch has been executed and is complete. However, the entry does not disappear. In fact, it seems that all the entries we’ve submitted this year just sit in the login page. 
Further, we’ve had some issues with the app randomly losing the entry we’re working on. When we have the app open all day and are entering inspections periodically it will just disappear. It won’t even be saved as a draft or reappear if we open and close the app again.
Hopefully that information is helpful. Thank you and have a nice week!
Elaine Desjarlais

**Email July 15**
Thanks for your continuous work on developing the new watercraft insecption app. It has been a positive highlight thus far in the season to have a recording process that is more efficient and timely. 
I have had it a few times where I have logged on to the app and there are inspections that are recorded as un-synced. However, shortly after logging on it appears that they will sync. I am not sure what causes it to not sync the first attempt.
I hope this feedback helps !
Cheyenne Hofer

**Email July 15**
_When you first log into the i-pad at the start of your shifts are you noticing any previously un-synced shift or inspections sitting on the screen that did not sync properly after you attempted to sync (for example from the day prior when you attempted to sync)?  Typically when they sync properly they will be gone but if they don’t sync properly they may just sit there._

I can say I have noticed this exact phenomena. I am usually able to get them to sync after a few tries, but those are only for those under my IDIR. I’m not sure if others have had this issue but I will encourage everyone to take a look at this email and respond.

Regards,
Sasha Zukewich

**Comment by AmirShayegh** [comment]
API has a character limit of 300 for comments, Inspect app has no limits.
So they API rejects submissions that go beyond the limit.
we should:
- Add character limit on Inspect app comment fields.
- On API side increase the limit since 300 seems to not be enough.
for the iOS side, it would be a 1 point ticket and i can set the limit to 300 or something higher if we increase the limit on API side
For syncing the next day:
if the device is online when the user submits, the records will be synced immediately. We cannot sync when the application is not launched (iOS operating system limits what apps can do when not launched for security and privacy reasons), so to make sure that the records get uploaded, users should open the app when they have an internet connection. if the sync doesn't get executed immediately, they can still tap the sync button and their records will be uploaded
